package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:03:27 by Hibernate Tools 5.3.0.Beta2

/**
 * PricMaestroEsclavo generated by hbm2java
 */
public class ClienteFactor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5361713044339073812L;
	private int pricCliente;
	private Double pricFactor;

	public ClienteFactor() {
	}

	public ClienteFactor(int pricCliente, Double pricFactor) {
		super();
		this.pricCliente = pricCliente;
		this.pricFactor = pricFactor;
	}

	public int getPricCliente() {
		return pricCliente;
	}

	public void setPricCliente(int pricCliente) {
		this.pricCliente = pricCliente;
	}

	public Double getPricFactor() {
		return pricFactor;
	}

	public void setPricFactor(Double pricFactor) {
		this.pricFactor = pricFactor;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
