package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:03:27 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * PricDescuentoXFamilias generated by hbm2java
 */
public class DescuentoXFamilias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2261744219677416566L;
	private int pricFamiliaId;
	private int pricFamiliaCliente;
	private int pricFamiliaListaPrecvta;
	private String pricCa01Clasif1;
	private BigDecimal pricFamiliaDescuento1;
	private BigDecimal pricFamiliaDescuento2;
	private Date pricFamiliaFechaDesde;
	private Date pricFamiliaFechaHasta;
	private BigDecimal pricFamiliaComision;
	private String pricReferencia;

	public DescuentoXFamilias() {
	}

	public DescuentoXFamilias(int pricFamiliaId, int pricFamiliaCliente, int pricFamiliaListaPrecvta, String pricCa01Clasif1, BigDecimal pricFamiliaDescuento1,
			BigDecimal pricFamiliaDescuento2, Date pricFamiliaFechaDesde, Date pricFamiliaFechaHasta, BigDecimal pricFamiliaComision, String pricReferencia) {
		super();
		this.pricFamiliaId = pricFamiliaId;
		this.pricFamiliaCliente = pricFamiliaCliente;
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
		this.pricCa01Clasif1 = pricCa01Clasif1;
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
		this.pricFamiliaComision = pricFamiliaComision;
		this.pricReferencia = pricReferencia;
	}

	public int getPricFamiliaId() {
		return pricFamiliaId;
	}

	public void setPricFamiliaId(int pricFamiliaId) {
		this.pricFamiliaId = pricFamiliaId;
	}

	public int getPricFamiliaCliente() {
		return pricFamiliaCliente;
	}

	public void setPricFamiliaCliente(int pricFamiliaCliente) {
		this.pricFamiliaCliente = pricFamiliaCliente;
	}

	public int getPricFamiliaListaPrecvta() {
		return pricFamiliaListaPrecvta;
	}

	public void setPricFamiliaListaPrecvta(int pricFamiliaListaPrecvta) {
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
	}

	public String getPricCa01Clasif1() {
		return pricCa01Clasif1;
	}

	public void setPricCa01Clasif1(String pricCa01Clasif1) {
		this.pricCa01Clasif1 = pricCa01Clasif1;
	}

	public BigDecimal getPricFamiliaDescuento1() {
		return pricFamiliaDescuento1;
	}

	public void setPricFamiliaDescuento1(BigDecimal pricFamiliaDescuento1) {
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
	}

	public BigDecimal getPricFamiliaDescuento2() {
		return pricFamiliaDescuento2;
	}

	public void setPricFamiliaDescuento2(BigDecimal pricFamiliaDescuento2) {
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
	}

	public Date getPricFamiliaFechaDesde() {
		return pricFamiliaFechaDesde;
	}

	public void setPricFamiliaFechaDesde(Date pricFamiliaFechaDesde) {
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
	}

	public Date getPricFamiliaFechaHasta() {
		return pricFamiliaFechaHasta;
	}

	public void setPricFamiliaFechaHasta(Date pricFamiliaFechaHasta) {
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
	}

	public BigDecimal getPricFamiliaComision() {
		return pricFamiliaComision;
	}

	public void setPricFamiliaComision(BigDecimal pricFamiliaComision) {
		this.pricFamiliaComision = pricFamiliaComision;
	}

	public String getPricReferencia() {
		return pricReferencia;
	}

	public void setPricReferencia(String pricReferencia) {
		this.pricReferencia = pricReferencia;
	}
	
	public boolean isvigente(Date date) {		
		return this.pricFamiliaFechaDesde.compareTo(date) > 0 && this.pricFamiliaFechaHasta.compareTo(date) > 0 ;
	}

}
