package ar.com.rollpaper.pricing.beans;
// Generated 18/05/2018 07:33:39 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * StocArts generated by hbm2java
 */
public class StocArts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5727210041861499322L;
	private int artsArticulo;
	private String artsNombre;
	private String artsArticuloEmp;
	private String artsArticuloImp;
	private String artsTipoArt;
	private String artsDescripcion;
	private String artsClasif1;
	private String artsClasif2;
	private String artsClasif3;
	private String artsClasif4;
	private String artsClasif5;
	private String artsClasif6;
	private String artsClasif7;
	private String artsClasif8;
	private String artsUnimedStock;
	private String artsCodbarStock;
	private boolean artsControlStock;
	private boolean artsConPartidas;
	private boolean artsNrosSerie;
	private boolean artsConTalles;
	private boolean artsSeVende;
	private boolean artsSeCompra;
	private Date artsFechaAlta;
	private Date artsFechaBaja;
	private boolean artsBloqueoMost;
	private BigDecimal artsPesoEmbUms;
	private BigDecimal artsCantBultUms;
	private String artsUnimedHomsto;
	private BigDecimal artsFactorHomsto;
	private String artsCuenta;
	private boolean artsSeProduce;
	private short artsConsumoCom;
	private short artsModoStocMin;
	private BigDecimal artsStockMinimo;
	private boolean artsGeneraMovstk;
	private String artsClasifUmArt;
	private BigDecimal artsPorcDmaxcaof;
	private boolean artsHabilPpp;
	private boolean artsAjusCantUms;
	private BigDecimal artsPorcmaxAjums;
	private boolean artsCosteoCiemes;
	private String artsTalle;
	private String artsColor;
	private Short artsDiviAsiCm;
	private Short artsEspecieGrano;
	private Short artsTipoGrano;
	private Short artsVariedadGrano;
	private String artsCuentaAnticipoLiq;
	private String artsCodigoProdCot;
	private Character artsCodigoUmCot;
	private BigDecimal artsFactorUmCot;
	private BigDecimal artsVolumenEmbUms;
	private String artsUnimedDim;
	private BigDecimal artsLargoDim;
	private BigDecimal artsAnchoDim;
	private BigDecimal artsAltoDim;
	private short artsDiasExisAntesUso;
	private byte artsUmsEsUcmi;
	private String artsUmUcmi;
	private BigDecimal artsFactorUmUcmi;
	private String artsCodbarUcmi;
	private String artsDescripcionWsAfip;
	private Integer artsDposConsumoComp;
	private String artsClasif1Cad1;
	private String artsClasif2Cad2;
	private String artsClasif3Cad3;
	private String artsClasif4Cad4;

	public StocArts() {
	}

	public StocArts(int artsArticulo, String artsNombre, String artsArticuloEmp, String artsArticuloImp,
			String artsTipoArt, String artsUnimedStock, boolean artsControlStock, boolean artsConPartidas,
			boolean artsNrosSerie, boolean artsConTalles, boolean artsSeVende, boolean artsSeCompra, Date artsFechaAlta,
			boolean artsBloqueoMost, BigDecimal artsPesoEmbUms, BigDecimal artsCantBultUms, BigDecimal artsFactorHomsto,
			String artsCuenta, boolean artsSeProduce, short artsConsumoCom, short artsModoStocMin,
			BigDecimal artsStockMinimo, boolean artsGeneraMovstk, BigDecimal artsPorcDmaxcaof, boolean artsHabilPpp,
			boolean artsAjusCantUms, BigDecimal artsPorcmaxAjums, boolean artsCosteoCiemes, BigDecimal artsFactorUmCot,
			BigDecimal artsVolumenEmbUms, short artsDiasExisAntesUso, byte artsUmsEsUcmi, BigDecimal artsFactorUmUcmi) {
		this.artsArticulo = artsArticulo;
		this.artsNombre = artsNombre;
		this.artsArticuloEmp = artsArticuloEmp;
		this.artsArticuloImp = artsArticuloImp;
		this.artsTipoArt = artsTipoArt;
		this.artsUnimedStock = artsUnimedStock;
		this.artsControlStock = artsControlStock;
		this.artsConPartidas = artsConPartidas;
		this.artsNrosSerie = artsNrosSerie;
		this.artsConTalles = artsConTalles;
		this.artsSeVende = artsSeVende;
		this.artsSeCompra = artsSeCompra;
		this.artsFechaAlta = artsFechaAlta;
		this.artsBloqueoMost = artsBloqueoMost;
		this.artsPesoEmbUms = artsPesoEmbUms;
		this.artsCantBultUms = artsCantBultUms;
		this.artsFactorHomsto = artsFactorHomsto;
		this.artsCuenta = artsCuenta;
		this.artsSeProduce = artsSeProduce;
		this.artsConsumoCom = artsConsumoCom;
		this.artsModoStocMin = artsModoStocMin;
		this.artsStockMinimo = artsStockMinimo;
		this.artsGeneraMovstk = artsGeneraMovstk;
		this.artsPorcDmaxcaof = artsPorcDmaxcaof;
		this.artsHabilPpp = artsHabilPpp;
		this.artsAjusCantUms = artsAjusCantUms;
		this.artsPorcmaxAjums = artsPorcmaxAjums;
		this.artsCosteoCiemes = artsCosteoCiemes;
		this.artsFactorUmCot = artsFactorUmCot;
		this.artsVolumenEmbUms = artsVolumenEmbUms;
		this.artsDiasExisAntesUso = artsDiasExisAntesUso;
		this.artsUmsEsUcmi = artsUmsEsUcmi;
		this.artsFactorUmUcmi = artsFactorUmUcmi;
	}

	public StocArts(int artsArticulo, String artsNombre, String artsArticuloEmp, String artsArticuloImp,
			String artsTipoArt, String artsDescripcion, String artsClasif1, String artsClasif2,
			String artsClasif3, String artsClasif4, String artsClasif5, String artsClasif6, String artsClasif7,
			String artsClasif8, String artsUnimedStock, String artsCodbarStock, boolean artsControlStock,
			boolean artsConPartidas, boolean artsNrosSerie, boolean artsConTalles, boolean artsSeVende,
			boolean artsSeCompra, Date artsFechaAlta, Date artsFechaBaja, boolean artsBloqueoMost,
			BigDecimal artsPesoEmbUms, BigDecimal artsCantBultUms, String artsUnimedHomsto, BigDecimal artsFactorHomsto,
			String artsCuenta, boolean artsSeProduce, short artsConsumoCom, short artsModoStocMin,
			BigDecimal artsStockMinimo, boolean artsGeneraMovstk, String artsClasifUmArt, BigDecimal artsPorcDmaxcaof,
			boolean artsHabilPpp, boolean artsAjusCantUms, BigDecimal artsPorcmaxAjums, boolean artsCosteoCiemes,
			String artsTalle, String artsColor, Short artsDiviAsiCm, Short artsEspecieGrano, Short artsTipoGrano,
			Short artsVariedadGrano, String artsCuentaAnticipoLiq, String artsCodigoProdCot, Character artsCodigoUmCot,
			BigDecimal artsFactorUmCot, BigDecimal artsVolumenEmbUms, String artsUnimedDim, BigDecimal artsLargoDim,
			BigDecimal artsAnchoDim, BigDecimal artsAltoDim, short artsDiasExisAntesUso, byte artsUmsEsUcmi,
			String artsUmUcmi, BigDecimal artsFactorUmUcmi, String artsCodbarUcmi, String artsDescripcionWsAfip,
			Integer artsDposConsumoComp, String artsClasif1Cad1, String artsClasif2Cad2, String artsClasif3Cad3,
			String artsClasif4Cad4) {
		this.artsArticulo = artsArticulo;
		this.artsNombre = artsNombre;
		this.artsArticuloEmp = artsArticuloEmp;
		this.artsArticuloImp = artsArticuloImp;
		this.artsTipoArt = artsTipoArt;
		this.artsDescripcion = artsDescripcion;
		this.artsClasif1 = artsClasif1;
		this.artsClasif2 = artsClasif2;
		this.artsClasif3 = artsClasif3;
		this.artsClasif4 = artsClasif4;
		this.artsClasif5 = artsClasif5;
		this.artsClasif6 = artsClasif6;
		this.artsClasif7 = artsClasif7;
		this.artsClasif8 = artsClasif8;
		this.artsUnimedStock = artsUnimedStock;
		this.artsCodbarStock = artsCodbarStock;
		this.artsControlStock = artsControlStock;
		this.artsConPartidas = artsConPartidas;
		this.artsNrosSerie = artsNrosSerie;
		this.artsConTalles = artsConTalles;
		this.artsSeVende = artsSeVende;
		this.artsSeCompra = artsSeCompra;
		this.artsFechaAlta = artsFechaAlta;
		this.artsFechaBaja = artsFechaBaja;
		this.artsBloqueoMost = artsBloqueoMost;
		this.artsPesoEmbUms = artsPesoEmbUms;
		this.artsCantBultUms = artsCantBultUms;
		this.artsUnimedHomsto = artsUnimedHomsto;
		this.artsFactorHomsto = artsFactorHomsto;
		this.artsCuenta = artsCuenta;
		this.artsSeProduce = artsSeProduce;
		this.artsConsumoCom = artsConsumoCom;
		this.artsModoStocMin = artsModoStocMin;
		this.artsStockMinimo = artsStockMinimo;
		this.artsGeneraMovstk = artsGeneraMovstk;
		this.artsClasifUmArt = artsClasifUmArt;
		this.artsPorcDmaxcaof = artsPorcDmaxcaof;
		this.artsHabilPpp = artsHabilPpp;
		this.artsAjusCantUms = artsAjusCantUms;
		this.artsPorcmaxAjums = artsPorcmaxAjums;
		this.artsCosteoCiemes = artsCosteoCiemes;
		this.artsTalle = artsTalle;
		this.artsColor = artsColor;
		this.artsDiviAsiCm = artsDiviAsiCm;
		this.artsEspecieGrano = artsEspecieGrano;
		this.artsTipoGrano = artsTipoGrano;
		this.artsVariedadGrano = artsVariedadGrano;
		this.artsCuentaAnticipoLiq = artsCuentaAnticipoLiq;
		this.artsCodigoProdCot = artsCodigoProdCot;
		this.artsCodigoUmCot = artsCodigoUmCot;
		this.artsFactorUmCot = artsFactorUmCot;
		this.artsVolumenEmbUms = artsVolumenEmbUms;
		this.artsUnimedDim = artsUnimedDim;
		this.artsLargoDim = artsLargoDim;
		this.artsAnchoDim = artsAnchoDim;
		this.artsAltoDim = artsAltoDim;
		this.artsDiasExisAntesUso = artsDiasExisAntesUso;
		this.artsUmsEsUcmi = artsUmsEsUcmi;
		this.artsUmUcmi = artsUmUcmi;
		this.artsFactorUmUcmi = artsFactorUmUcmi;
		this.artsCodbarUcmi = artsCodbarUcmi;
		this.artsDescripcionWsAfip = artsDescripcionWsAfip;
		this.artsDposConsumoComp = artsDposConsumoComp;
		this.artsClasif1Cad1 = artsClasif1Cad1;
		this.artsClasif2Cad2 = artsClasif2Cad2;
		this.artsClasif3Cad3 = artsClasif3Cad3;
		this.artsClasif4Cad4 = artsClasif4Cad4;
	}

	public int getArtsArticulo() {
		return this.artsArticulo;
	}

	public void setArtsArticulo(int artsArticulo) {
		this.artsArticulo = artsArticulo;
	}

	public String getArtsNombre() {
		return this.artsNombre;
	}

	public void setArtsNombre(String artsNombre) {
		this.artsNombre = artsNombre;
	}

	public String getArtsArticuloEmp() {
		return this.artsArticuloEmp;
	}

	public void setArtsArticuloEmp(String artsArticuloEmp) {
		this.artsArticuloEmp = artsArticuloEmp;
	}

	public String getArtsArticuloImp() {
		return this.artsArticuloImp;
	}

	public void setArtsArticuloImp(String artsArticuloImp) {
		this.artsArticuloImp = artsArticuloImp;
	}

	public String getArtsTipoArt() {
		return this.artsTipoArt;
	}

	public void setArtsTipoArt(String artsTipoArt) {
		this.artsTipoArt = artsTipoArt;
	}

	public String getArtsDescripcion() {
		return this.artsDescripcion;
	}

	public void setArtsDescripcion(String artsDescripcion) {
		this.artsDescripcion = artsDescripcion;
	}

	public String getArtsClasif1() {
		return this.artsClasif1;
	}

	public void setArtsClasif1(String artsClasif1) {
		this.artsClasif1 = artsClasif1;
	}

	public String getArtsClasif2() {
		return this.artsClasif2;
	}

	public void setArtsClasif2(String artsClasif2) {
		this.artsClasif2 = artsClasif2;
	}

	public String getArtsClasif3() {
		return this.artsClasif3;
	}

	public void setArtsClasif3(String artsClasif3) {
		this.artsClasif3 = artsClasif3;
	}

	public String getArtsClasif4() {
		return this.artsClasif4;
	}

	public void setArtsClasif4(String artsClasif4) {
		this.artsClasif4 = artsClasif4;
	}

	public String getArtsClasif5() {
		return this.artsClasif5;
	}

	public void setArtsClasif5(String artsClasif5) {
		this.artsClasif5 = artsClasif5;
	}

	public String getArtsClasif6() {
		return this.artsClasif6;
	}

	public void setArtsClasif6(String artsClasif6) {
		this.artsClasif6 = artsClasif6;
	}

	public String getArtsClasif7() {
		return this.artsClasif7;
	}

	public void setArtsClasif7(String artsClasif7) {
		this.artsClasif7 = artsClasif7;
	}

	public String getArtsClasif8() {
		return this.artsClasif8;
	}

	public void setArtsClasif8(String artsClasif8) {
		this.artsClasif8 = artsClasif8;
	}

	public String getArtsUnimedStock() {
		return this.artsUnimedStock;
	}

	public void setArtsUnimedStock(String artsUnimedStock) {
		this.artsUnimedStock = artsUnimedStock;
	}

	public String getArtsCodbarStock() {
		return this.artsCodbarStock;
	}

	public void setArtsCodbarStock(String artsCodbarStock) {
		this.artsCodbarStock = artsCodbarStock;
	}

	public boolean isArtsControlStock() {
		return this.artsControlStock;
	}

	public void setArtsControlStock(boolean artsControlStock) {
		this.artsControlStock = artsControlStock;
	}

	public boolean isArtsConPartidas() {
		return this.artsConPartidas;
	}

	public void setArtsConPartidas(boolean artsConPartidas) {
		this.artsConPartidas = artsConPartidas;
	}

	public boolean isArtsNrosSerie() {
		return this.artsNrosSerie;
	}

	public void setArtsNrosSerie(boolean artsNrosSerie) {
		this.artsNrosSerie = artsNrosSerie;
	}

	public boolean isArtsConTalles() {
		return this.artsConTalles;
	}

	public void setArtsConTalles(boolean artsConTalles) {
		this.artsConTalles = artsConTalles;
	}

	public boolean isArtsSeVende() {
		return this.artsSeVende;
	}

	public void setArtsSeVende(boolean artsSeVende) {
		this.artsSeVende = artsSeVende;
	}

	public boolean isArtsSeCompra() {
		return this.artsSeCompra;
	}

	public void setArtsSeCompra(boolean artsSeCompra) {
		this.artsSeCompra = artsSeCompra;
	}

	public Date getArtsFechaAlta() {
		return this.artsFechaAlta;
	}

	public void setArtsFechaAlta(Date artsFechaAlta) {
		this.artsFechaAlta = artsFechaAlta;
	}

	public Date getArtsFechaBaja() {
		return this.artsFechaBaja;
	}

	public void setArtsFechaBaja(Date artsFechaBaja) {
		this.artsFechaBaja = artsFechaBaja;
	}

	public boolean isArtsBloqueoMost() {
		return this.artsBloqueoMost;
	}

	public void setArtsBloqueoMost(boolean artsBloqueoMost) {
		this.artsBloqueoMost = artsBloqueoMost;
	}

	public BigDecimal getArtsPesoEmbUms() {
		return this.artsPesoEmbUms;
	}

	public void setArtsPesoEmbUms(BigDecimal artsPesoEmbUms) {
		this.artsPesoEmbUms = artsPesoEmbUms;
	}

	public BigDecimal getArtsCantBultUms() {
		return this.artsCantBultUms;
	}

	public void setArtsCantBultUms(BigDecimal artsCantBultUms) {
		this.artsCantBultUms = artsCantBultUms;
	}

	public String getArtsUnimedHomsto() {
		return this.artsUnimedHomsto;
	}

	public void setArtsUnimedHomsto(String artsUnimedHomsto) {
		this.artsUnimedHomsto = artsUnimedHomsto;
	}

	public BigDecimal getArtsFactorHomsto() {
		return this.artsFactorHomsto;
	}

	public void setArtsFactorHomsto(BigDecimal artsFactorHomsto) {
		this.artsFactorHomsto = artsFactorHomsto;
	}

	public String getArtsCuenta() {
		return this.artsCuenta;
	}

	public void setArtsCuenta(String artsCuenta) {
		this.artsCuenta = artsCuenta;
	}

	public boolean isArtsSeProduce() {
		return this.artsSeProduce;
	}

	public void setArtsSeProduce(boolean artsSeProduce) {
		this.artsSeProduce = artsSeProduce;
	}

	public short getArtsConsumoCom() {
		return this.artsConsumoCom;
	}

	public void setArtsConsumoCom(short artsConsumoCom) {
		this.artsConsumoCom = artsConsumoCom;
	}

	public short getArtsModoStocMin() {
		return this.artsModoStocMin;
	}

	public void setArtsModoStocMin(short artsModoStocMin) {
		this.artsModoStocMin = artsModoStocMin;
	}

	public BigDecimal getArtsStockMinimo() {
		return this.artsStockMinimo;
	}

	public void setArtsStockMinimo(BigDecimal artsStockMinimo) {
		this.artsStockMinimo = artsStockMinimo;
	}

	public boolean isArtsGeneraMovstk() {
		return this.artsGeneraMovstk;
	}

	public void setArtsGeneraMovstk(boolean artsGeneraMovstk) {
		this.artsGeneraMovstk = artsGeneraMovstk;
	}

	public String getArtsClasifUmArt() {
		return this.artsClasifUmArt;
	}

	public void setArtsClasifUmArt(String artsClasifUmArt) {
		this.artsClasifUmArt = artsClasifUmArt;
	}

	public BigDecimal getArtsPorcDmaxcaof() {
		return this.artsPorcDmaxcaof;
	}

	public void setArtsPorcDmaxcaof(BigDecimal artsPorcDmaxcaof) {
		this.artsPorcDmaxcaof = artsPorcDmaxcaof;
	}

	public boolean isArtsHabilPpp() {
		return this.artsHabilPpp;
	}

	public void setArtsHabilPpp(boolean artsHabilPpp) {
		this.artsHabilPpp = artsHabilPpp;
	}

	public boolean isArtsAjusCantUms() {
		return this.artsAjusCantUms;
	}

	public void setArtsAjusCantUms(boolean artsAjusCantUms) {
		this.artsAjusCantUms = artsAjusCantUms;
	}

	public BigDecimal getArtsPorcmaxAjums() {
		return this.artsPorcmaxAjums;
	}

	public void setArtsPorcmaxAjums(BigDecimal artsPorcmaxAjums) {
		this.artsPorcmaxAjums = artsPorcmaxAjums;
	}

	public boolean isArtsCosteoCiemes() {
		return this.artsCosteoCiemes;
	}

	public void setArtsCosteoCiemes(boolean artsCosteoCiemes) {
		this.artsCosteoCiemes = artsCosteoCiemes;
	}

	public String getArtsTalle() {
		return this.artsTalle;
	}

	public void setArtsTalle(String artsTalle) {
		this.artsTalle = artsTalle;
	}

	public String getArtsColor() {
		return this.artsColor;
	}

	public void setArtsColor(String artsColor) {
		this.artsColor = artsColor;
	}

	public Short getArtsDiviAsiCm() {
		return this.artsDiviAsiCm;
	}

	public void setArtsDiviAsiCm(Short artsDiviAsiCm) {
		this.artsDiviAsiCm = artsDiviAsiCm;
	}

	public Short getArtsEspecieGrano() {
		return this.artsEspecieGrano;
	}

	public void setArtsEspecieGrano(Short artsEspecieGrano) {
		this.artsEspecieGrano = artsEspecieGrano;
	}

	public Short getArtsTipoGrano() {
		return this.artsTipoGrano;
	}

	public void setArtsTipoGrano(Short artsTipoGrano) {
		this.artsTipoGrano = artsTipoGrano;
	}

	public Short getArtsVariedadGrano() {
		return this.artsVariedadGrano;
	}

	public void setArtsVariedadGrano(Short artsVariedadGrano) {
		this.artsVariedadGrano = artsVariedadGrano;
	}

	public String getArtsCuentaAnticipoLiq() {
		return this.artsCuentaAnticipoLiq;
	}

	public void setArtsCuentaAnticipoLiq(String artsCuentaAnticipoLiq) {
		this.artsCuentaAnticipoLiq = artsCuentaAnticipoLiq;
	}

	public String getArtsCodigoProdCot() {
		return this.artsCodigoProdCot;
	}

	public void setArtsCodigoProdCot(String artsCodigoProdCot) {
		this.artsCodigoProdCot = artsCodigoProdCot;
	}

	public Character getArtsCodigoUmCot() {
		return this.artsCodigoUmCot;
	}

	public void setArtsCodigoUmCot(Character artsCodigoUmCot) {
		this.artsCodigoUmCot = artsCodigoUmCot;
	}

	public BigDecimal getArtsFactorUmCot() {
		return this.artsFactorUmCot;
	}

	public void setArtsFactorUmCot(BigDecimal artsFactorUmCot) {
		this.artsFactorUmCot = artsFactorUmCot;
	}

	public BigDecimal getArtsVolumenEmbUms() {
		return this.artsVolumenEmbUms;
	}

	public void setArtsVolumenEmbUms(BigDecimal artsVolumenEmbUms) {
		this.artsVolumenEmbUms = artsVolumenEmbUms;
	}

	public String getArtsUnimedDim() {
		return this.artsUnimedDim;
	}

	public void setArtsUnimedDim(String artsUnimedDim) {
		this.artsUnimedDim = artsUnimedDim;
	}

	public BigDecimal getArtsLargoDim() {
		return this.artsLargoDim;
	}

	public void setArtsLargoDim(BigDecimal artsLargoDim) {
		this.artsLargoDim = artsLargoDim;
	}

	public BigDecimal getArtsAnchoDim() {
		return this.artsAnchoDim;
	}

	public void setArtsAnchoDim(BigDecimal artsAnchoDim) {
		this.artsAnchoDim = artsAnchoDim;
	}

	public BigDecimal getArtsAltoDim() {
		return this.artsAltoDim;
	}

	public void setArtsAltoDim(BigDecimal artsAltoDim) {
		this.artsAltoDim = artsAltoDim;
	}

	public short getArtsDiasExisAntesUso() {
		return this.artsDiasExisAntesUso;
	}

	public void setArtsDiasExisAntesUso(short artsDiasExisAntesUso) {
		this.artsDiasExisAntesUso = artsDiasExisAntesUso;
	}

	public byte getArtsUmsEsUcmi() {
		return this.artsUmsEsUcmi;
	}

	public void setArtsUmsEsUcmi(byte artsUmsEsUcmi) {
		this.artsUmsEsUcmi = artsUmsEsUcmi;
	}

	public String getArtsUmUcmi() {
		return this.artsUmUcmi;
	}

	public void setArtsUmUcmi(String artsUmUcmi) {
		this.artsUmUcmi = artsUmUcmi;
	}

	public BigDecimal getArtsFactorUmUcmi() {
		return this.artsFactorUmUcmi;
	}

	public void setArtsFactorUmUcmi(BigDecimal artsFactorUmUcmi) {
		this.artsFactorUmUcmi = artsFactorUmUcmi;
	}

	public String getArtsCodbarUcmi() {
		return this.artsCodbarUcmi;
	}

	public void setArtsCodbarUcmi(String artsCodbarUcmi) {
		this.artsCodbarUcmi = artsCodbarUcmi;
	}

	public String getArtsDescripcionWsAfip() {
		return this.artsDescripcionWsAfip;
	}

	public void setArtsDescripcionWsAfip(String artsDescripcionWsAfip) {
		this.artsDescripcionWsAfip = artsDescripcionWsAfip;
	}

	public Integer getArtsDposConsumoComp() {
		return this.artsDposConsumoComp;
	}

	public void setArtsDposConsumoComp(Integer artsDposConsumoComp) {
		this.artsDposConsumoComp = artsDposConsumoComp;
	}

	public String getArtsClasif1Cad1() {
		return this.artsClasif1Cad1;
	}

	public void setArtsClasif1Cad1(String artsClasif1Cad1) {
		this.artsClasif1Cad1 = artsClasif1Cad1;
	}

	public String getArtsClasif2Cad2() {
		return this.artsClasif2Cad2;
	}

	public void setArtsClasif2Cad2(String artsClasif2Cad2) {
		this.artsClasif2Cad2 = artsClasif2Cad2;
	}

	public String getArtsClasif3Cad3() {
		return this.artsClasif3Cad3;
	}

	public void setArtsClasif3Cad3(String artsClasif3Cad3) {
		this.artsClasif3Cad3 = artsClasif3Cad3;
	}

	public String getArtsClasif4Cad4() {
		return this.artsClasif4Cad4;
	}

	public void setArtsClasif4Cad4(String artsClasif4Cad4) {
		this.artsClasif4Cad4 = artsClasif4Cad4;
	}

}
