package ar.com.rollpaper.pricing.beans;
// Generated 21/05/2018 20:09:21 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * VentArpc generated by hbm2java
 */
public class VentArpc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8567296207072075669L;
	private VentArpcId id;
	private CcobClie ccobClie;
	private BigDecimal arpcPrecioVta;
	private String arpcMoneda;
	private BigDecimal arpcPrecioVtaAn;
	private String arpcMonedaAnt;
	private Date arpcFechaUltAct;

	public VentArpc() {
	}

	public VentArpc(VentArpcId id, CcobClie ccobClie, BigDecimal arpcPrecioVta, String arpcMoneda,
			BigDecimal arpcPrecioVtaAn, Date arpcFechaUltAct) {
		this.id = id;
		this.ccobClie = ccobClie;
		this.arpcPrecioVta = arpcPrecioVta;
		this.arpcMoneda = arpcMoneda;
		this.arpcPrecioVtaAn = arpcPrecioVtaAn;
		this.arpcFechaUltAct = arpcFechaUltAct;
	}

	public VentArpc(VentArpcId id, CcobClie ccobClie, BigDecimal arpcPrecioVta, String arpcMoneda,
			BigDecimal arpcPrecioVtaAn, String arpcMonedaAnt, Date arpcFechaUltAct) {
		this.id = id;
		this.ccobClie = ccobClie;
		this.arpcPrecioVta = arpcPrecioVta;
		this.arpcMoneda = arpcMoneda;
		this.arpcPrecioVtaAn = arpcPrecioVtaAn;
		this.arpcMonedaAnt = arpcMonedaAnt;
		this.arpcFechaUltAct = arpcFechaUltAct;
	}

	public VentArpcId getId() {
		return this.id;
	}

	public void setId(VentArpcId id) {
		this.id = id;
	}

	public CcobClie getCcobClie() {
		return this.ccobClie;
	}

	public void setCcobClie(CcobClie ccobClie) {
		this.ccobClie = ccobClie;
	}

	public BigDecimal getArpcPrecioVta() {
		return this.arpcPrecioVta;
	}

	public void setArpcPrecioVta(BigDecimal arpcPrecioVta) {
		this.arpcPrecioVta = arpcPrecioVta;
	}

	public String getArpcMoneda() {
		return this.arpcMoneda;
	}

	public void setArpcMoneda(String arpcMoneda) {
		this.arpcMoneda = arpcMoneda;
	}

	public BigDecimal getArpcPrecioVtaAn() {
		return this.arpcPrecioVtaAn;
	}

	public void setArpcPrecioVtaAn(BigDecimal arpcPrecioVtaAn) {
		this.arpcPrecioVtaAn = arpcPrecioVtaAn;
	}

	public String getArpcMonedaAnt() {
		return this.arpcMonedaAnt;
	}

	public void setArpcMonedaAnt(String arpcMonedaAnt) {
		this.arpcMonedaAnt = arpcMonedaAnt;
	}

	public Date getArpcFechaUltAct() {
		return this.arpcFechaUltAct;
	}

	public void setArpcFechaUltAct(Date arpcFechaUltAct) {
		this.arpcFechaUltAct = arpcFechaUltAct;
	}

}
