//TODO falta agregar el campo id familia

package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:03:27 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * PricDescuentoXFamilias generated by hbm2java
 */
public class DescuentoXFamilias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2261744219677416566L;
	private int pricFamiliaId;
	private int pricFamiliaCliente;
	private String pricFamiliaListaPrecvta;
	private BigDecimal pricFamiliaDescuento1;
	private BigDecimal pricFamiliaDescuento2;
	private Date pricFamiliaFechaDesde;
	private Date pricFamiliaFechaHasta;
	private BigDecimal pricFamiliaComision;
	private String pricReferencia;

	public DescuentoXFamilias() {
	}

	public DescuentoXFamilias(int pricFamiliaId, int pricFamiliaCliente, String pricFamiliaListaPrecvta, BigDecimal pricFamiliaDescuento1, BigDecimal pricFamiliaDescuento2,
			Date pricFamiliaFechaDesde, Date pricFamiliaFechaHasta, BigDecimal pricFamiliaComision, String pricReferencia) {
		super();
		this.pricFamiliaId = pricFamiliaId;
		this.pricFamiliaCliente = pricFamiliaCliente;
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
		this.pricFamiliaComision = pricFamiliaComision;
		this.pricReferencia = pricReferencia;
	}

	public int getPricFamiliaId() {
		return pricFamiliaId;
	}

	public void setPricFamiliaId(int pricFamiliaId) {
		this.pricFamiliaId = pricFamiliaId;
	}

	public int getPricFamiliaCliente() {
		return pricFamiliaCliente;
	}

	public void setPricFamiliaCliente(int pricFamiliaCliente) {
		this.pricFamiliaCliente = pricFamiliaCliente;
	}

	public String getPricFamiliaListaPrecvta() {
		return pricFamiliaListaPrecvta;
	}

	public void setPricFamiliaListaPrecvta(String pricFamiliaListaPrecvta) {
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
	}

	public BigDecimal getPricFamiliaDescuento1() {
		return pricFamiliaDescuento1;
	}

	public void setPricFamiliaDescuento1(BigDecimal pricFamiliaDescuento1) {
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
	}

	public BigDecimal getPricFamiliaDescuento2() {
		return pricFamiliaDescuento2;
	}

	public void setPricFamiliaDescuento2(BigDecimal pricFamiliaDescuento2) {
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
	}

	public Date getPricFamiliaFechaDesde() {
		return pricFamiliaFechaDesde;
	}

	public void setPricFamiliaFechaDesde(Date pricFamiliaFechaDesde) {
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
	}

	public Date getPricFamiliaFechaHasta() {
		return pricFamiliaFechaHasta;
	}

	public void setPricFamiliaFechaHasta(Date pricFamiliaFechaHasta) {
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
	}

	public BigDecimal getPricFamiliaComision() {
		return pricFamiliaComision;
	}

	public void setPricFamiliaComision(BigDecimal pricFamiliaComision) {
		this.pricFamiliaComision = pricFamiliaComision;
	}

	public String getPricReferencia() {
		return pricReferencia;
	}

	public void setPricReferencia(String pricReferencia) {
		this.pricReferencia = pricReferencia;
	}
}
