package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:03:27 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * PricDescuentoXFamilias generated by hbm2java
 */
public class DescuentoXFamilias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2261744219677416566L;
	private int pricFamiliaId;
	private int pricFamiliaCliente;
	private int pricFamiliaListaPrecvta;
	private int pricFamiliaDescuento1;
	private BigDecimal pricFamiliaDescuento2;
	private Date pricFamiliaFechaDesde;
	private Date pricFamiliaFechaHasta;
	private String pricReferencia;

	public DescuentoXFamilias() {
	}

	public DescuentoXFamilias(int pricFamiliaId, int pricFamiliaCliente, int pricFamiliaListaPrecvta,
			int pricFamiliaDescuento1, BigDecimal pricFamiliaDescuento2, Date pricFamiliaFechaDesde,
			Date pricFamiliaFechaHasta) {
		this.pricFamiliaId = pricFamiliaId;
		this.pricFamiliaCliente = pricFamiliaCliente;
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
	}

	public DescuentoXFamilias(int pricFamiliaId, int pricFamiliaCliente, int pricFamiliaListaPrecvta,
			int pricFamiliaDescuento1, BigDecimal pricFamiliaDescuento2, Date pricFamiliaFechaDesde,
			Date pricFamiliaFechaHasta, String pricReferencia) {
		this.pricFamiliaId = pricFamiliaId;
		this.pricFamiliaCliente = pricFamiliaCliente;
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
		this.pricReferencia = pricReferencia;
	}

	public int getPricFamiliaId() {
		return this.pricFamiliaId;
	}

	public void setPricFamiliaId(int pricFamiliaId) {
		this.pricFamiliaId = pricFamiliaId;
	}

	public int getPricFamiliaCliente() {
		return this.pricFamiliaCliente;
	}

	public void setPricFamiliaCliente(int pricFamiliaCliente) {
		this.pricFamiliaCliente = pricFamiliaCliente;
	}

	public int getPricFamiliaListaPrecvta() {
		return this.pricFamiliaListaPrecvta;
	}

	public void setPricFamiliaListaPrecvta(int pricFamiliaListaPrecvta) {
		this.pricFamiliaListaPrecvta = pricFamiliaListaPrecvta;
	}

	public int getPricFamiliaDescuento1() {
		return this.pricFamiliaDescuento1;
	}

	public void setPricFamiliaDescuento1(int pricFamiliaDescuento1) {
		this.pricFamiliaDescuento1 = pricFamiliaDescuento1;
	}

	public BigDecimal getPricFamiliaDescuento2() {
		return this.pricFamiliaDescuento2;
	}

	public void setPricFamiliaDescuento2(BigDecimal pricFamiliaDescuento2) {
		this.pricFamiliaDescuento2 = pricFamiliaDescuento2;
	}

	public Date getPricFamiliaFechaDesde() {
		return this.pricFamiliaFechaDesde;
	}

	public void setPricFamiliaFechaDesde(Date pricFamiliaFechaDesde) {
		this.pricFamiliaFechaDesde = pricFamiliaFechaDesde;
	}

	public Date getPricFamiliaFechaHasta() {
		return this.pricFamiliaFechaHasta;
	}

	public void setPricFamiliaFechaHasta(Date pricFamiliaFechaHasta) {
		this.pricFamiliaFechaHasta = pricFamiliaFechaHasta;
	}

	public String getPricReferencia() {
		return this.pricReferencia;
	}

	public void setPricReferencia(String pricReferencia) {
		this.pricReferencia = pricReferencia;
	}

}
