package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:15:54 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * SistMone generated by hbm2java
 */
public class SistMone implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String moneMoneda;
	private String moneNombre;
	private String moneSimbolo;
	private boolean moneLocal;
	private boolean moneConversion;
	private String moneTipoMonAfip;
	private boolean moneUtilizable;
	private short moneCantDecimRedImpuestos;
	private Set ventArpvsForArpvMoneda = new HashSet(0);
	private Set ventLipvs = new HashSet(0);
	private Set ventArpvsForArpvMonedaAnt = new HashSet(0);

	public SistMone() {
	}

	public SistMone(String moneMoneda, String moneNombre, String moneSimbolo, boolean moneLocal, boolean moneConversion,
			boolean moneUtilizable, short moneCantDecimRedImpuestos) {
		this.moneMoneda = moneMoneda;
		this.moneNombre = moneNombre;
		this.moneSimbolo = moneSimbolo;
		this.moneLocal = moneLocal;
		this.moneConversion = moneConversion;
		this.moneUtilizable = moneUtilizable;
		this.moneCantDecimRedImpuestos = moneCantDecimRedImpuestos;
	}

	public SistMone(String moneMoneda, String moneNombre, String moneSimbolo, boolean moneLocal, boolean moneConversion,
			String moneTipoMonAfip, boolean moneUtilizable, short moneCantDecimRedImpuestos, Set ventArpvsForArpvMoneda,
			Set ventLipvs, Set ventArpvsForArpvMonedaAnt) {
		this.moneMoneda = moneMoneda;
		this.moneNombre = moneNombre;
		this.moneSimbolo = moneSimbolo;
		this.moneLocal = moneLocal;
		this.moneConversion = moneConversion;
		this.moneTipoMonAfip = moneTipoMonAfip;
		this.moneUtilizable = moneUtilizable;
		this.moneCantDecimRedImpuestos = moneCantDecimRedImpuestos;
		this.ventArpvsForArpvMoneda = ventArpvsForArpvMoneda;
		this.ventLipvs = ventLipvs;
		this.ventArpvsForArpvMonedaAnt = ventArpvsForArpvMonedaAnt;
	}

	public String getMoneMoneda() {
		return this.moneMoneda;
	}

	public void setMoneMoneda(String moneMoneda) {
		this.moneMoneda = moneMoneda;
	}

	public String getMoneNombre() {
		return this.moneNombre;
	}

	public void setMoneNombre(String moneNombre) {
		this.moneNombre = moneNombre;
	}

	public String getMoneSimbolo() {
		return this.moneSimbolo;
	}

	public void setMoneSimbolo(String moneSimbolo) {
		this.moneSimbolo = moneSimbolo;
	}

	public boolean isMoneLocal() {
		return this.moneLocal;
	}

	public void setMoneLocal(boolean moneLocal) {
		this.moneLocal = moneLocal;
	}

	public boolean isMoneConversion() {
		return this.moneConversion;
	}

	public void setMoneConversion(boolean moneConversion) {
		this.moneConversion = moneConversion;
	}

	public String getMoneTipoMonAfip() {
		return this.moneTipoMonAfip;
	}

	public void setMoneTipoMonAfip(String moneTipoMonAfip) {
		this.moneTipoMonAfip = moneTipoMonAfip;
	}

	public boolean isMoneUtilizable() {
		return this.moneUtilizable;
	}

	public void setMoneUtilizable(boolean moneUtilizable) {
		this.moneUtilizable = moneUtilizable;
	}

	public short getMoneCantDecimRedImpuestos() {
		return this.moneCantDecimRedImpuestos;
	}

	public void setMoneCantDecimRedImpuestos(short moneCantDecimRedImpuestos) {
		this.moneCantDecimRedImpuestos = moneCantDecimRedImpuestos;
	}

	public Set getVentArpvsForArpvMoneda() {
		return this.ventArpvsForArpvMoneda;
	}

	public void setVentArpvsForArpvMoneda(Set ventArpvsForArpvMoneda) {
		this.ventArpvsForArpvMoneda = ventArpvsForArpvMoneda;
	}

	public Set getVentLipvs() {
		return this.ventLipvs;
	}

	public void setVentLipvs(Set ventLipvs) {
		this.ventLipvs = ventLipvs;
	}

	public Set getVentArpvsForArpvMonedaAnt() {
		return this.ventArpvsForArpvMonedaAnt;
	}

	public void setVentArpvsForArpvMonedaAnt(Set ventArpvsForArpvMonedaAnt) {
		this.ventArpvsForArpvMonedaAnt = ventArpvsForArpvMonedaAnt;
	}

}
