package ar.com.rollpaper.pricing.beans;        


/**
 * SistUnim generated by hbm2java
 */
public class SistUnim implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3049401397345839420L;
	private String unimUnimed;
	private String unimNombre;
	
	public SistUnim(String unimUnimed, String unimNombre) {
		super();
		this.unimUnimed = unimUnimed;
		this.unimNombre = unimNombre;
	}

	public SistUnim() {
		super();
	}

	public String getUnimUnimed() {
		return unimUnimed;
	}

	public void setUnimUnimed(String unimUnimed) {
		this.unimUnimed = unimUnimed;
	}

	public String getUnimNombre() {
		return unimNombre;
	}

	public void setUnimNombre(String unimNombre) {
		this.unimNombre = unimNombre;
	}
	
}
