package ar.com.rollpaper.pricing.beans;
// Generated 21/05/2018 20:09:21 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * VentCliv generated by hbm2java
 */
public class VentCliv implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6034169847007905921L;
	private int clivCliente;
	private CcobClie ccobClie;
	private Integer clivListaPrecvta;
	private BigDecimal clivMonCredTot;
	private BigDecimal clivMonCredCte;
	private BigDecimal clivMonCteVenc;
	private short clivDiasCteVenc;
	private short clivDiasAtrasopa;
	private boolean clivSoloArtrestr;
	private BigDecimal clivMonEntVal;
	private boolean clivHabilOfertas;
	private Integer clivListaPrecioAcopio;
	private short clivDiasMonEntVal;

	public VentCliv() {
	}

	public VentCliv(CcobClie ccobClie, BigDecimal clivMonCredTot, BigDecimal clivMonCredCte, BigDecimal clivMonCteVenc,
			short clivDiasCteVenc, short clivDiasAtrasopa, boolean clivSoloArtrestr, BigDecimal clivMonEntVal,
			boolean clivHabilOfertas, short clivDiasMonEntVal) {
		this.ccobClie = ccobClie;
		this.clivMonCredTot = clivMonCredTot;
		this.clivMonCredCte = clivMonCredCte;
		this.clivMonCteVenc = clivMonCteVenc;
		this.clivDiasCteVenc = clivDiasCteVenc;
		this.clivDiasAtrasopa = clivDiasAtrasopa;
		this.clivSoloArtrestr = clivSoloArtrestr;
		this.clivMonEntVal = clivMonEntVal;
		this.clivHabilOfertas = clivHabilOfertas;
		this.clivDiasMonEntVal = clivDiasMonEntVal;
	}

	public VentCliv(CcobClie ccobClie, Integer clivListaPrecvta, BigDecimal clivMonCredTot, BigDecimal clivMonCredCte,
			BigDecimal clivMonCteVenc, short clivDiasCteVenc, short clivDiasAtrasopa, boolean clivSoloArtrestr,
			BigDecimal clivMonEntVal, boolean clivHabilOfertas, Integer clivListaPrecioAcopio,
			short clivDiasMonEntVal) {
		this.ccobClie = ccobClie;
		this.clivListaPrecvta = clivListaPrecvta;
		this.clivMonCredTot = clivMonCredTot;
		this.clivMonCredCte = clivMonCredCte;
		this.clivMonCteVenc = clivMonCteVenc;
		this.clivDiasCteVenc = clivDiasCteVenc;
		this.clivDiasAtrasopa = clivDiasAtrasopa;
		this.clivSoloArtrestr = clivSoloArtrestr;
		this.clivMonEntVal = clivMonEntVal;
		this.clivHabilOfertas = clivHabilOfertas;
		this.clivListaPrecioAcopio = clivListaPrecioAcopio;
		this.clivDiasMonEntVal = clivDiasMonEntVal;
	}

	public int getClivCliente() {
		return this.clivCliente;
	}

	public void setClivCliente(int clivCliente) {
		this.clivCliente = clivCliente;
	}

	public CcobClie getCcobClie() {
		return this.ccobClie;
	}

	public void setCcobClie(CcobClie ccobClie) {
		this.ccobClie = ccobClie;
	}

	public Integer getClivListaPrecvta() {
		return this.clivListaPrecvta;
	}

	public void setClivListaPrecvta(Integer clivListaPrecvta) {
		this.clivListaPrecvta = clivListaPrecvta;
	}

	public BigDecimal getClivMonCredTot() {
		return this.clivMonCredTot;
	}

	public void setClivMonCredTot(BigDecimal clivMonCredTot) {
		this.clivMonCredTot = clivMonCredTot;
	}

	public BigDecimal getClivMonCredCte() {
		return this.clivMonCredCte;
	}

	public void setClivMonCredCte(BigDecimal clivMonCredCte) {
		this.clivMonCredCte = clivMonCredCte;
	}

	public BigDecimal getClivMonCteVenc() {
		return this.clivMonCteVenc;
	}

	public void setClivMonCteVenc(BigDecimal clivMonCteVenc) {
		this.clivMonCteVenc = clivMonCteVenc;
	}

	public short getClivDiasCteVenc() {
		return this.clivDiasCteVenc;
	}

	public void setClivDiasCteVenc(short clivDiasCteVenc) {
		this.clivDiasCteVenc = clivDiasCteVenc;
	}

	public short getClivDiasAtrasopa() {
		return this.clivDiasAtrasopa;
	}

	public void setClivDiasAtrasopa(short clivDiasAtrasopa) {
		this.clivDiasAtrasopa = clivDiasAtrasopa;
	}

	public boolean isClivSoloArtrestr() {
		return this.clivSoloArtrestr;
	}

	public void setClivSoloArtrestr(boolean clivSoloArtrestr) {
		this.clivSoloArtrestr = clivSoloArtrestr;
	}

	public BigDecimal getClivMonEntVal() {
		return this.clivMonEntVal;
	}

	public void setClivMonEntVal(BigDecimal clivMonEntVal) {
		this.clivMonEntVal = clivMonEntVal;
	}

	public boolean isClivHabilOfertas() {
		return this.clivHabilOfertas;
	}

	public void setClivHabilOfertas(boolean clivHabilOfertas) {
		this.clivHabilOfertas = clivHabilOfertas;
	}

	public Integer getClivListaPrecioAcopio() {
		return this.clivListaPrecioAcopio;
	}

	public void setClivListaPrecioAcopio(Integer clivListaPrecioAcopio) {
		this.clivListaPrecioAcopio = clivListaPrecioAcopio;
	}

	public short getClivDiasMonEntVal() {
		return this.clivDiasMonEntVal;
	}

	public void setClivDiasMonEntVal(short clivDiasMonEntVal) {
		this.clivDiasMonEntVal = clivDiasMonEntVal;
	}

}
