package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:15:54 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VentLipv generated by hbm2java
 */
public class VentLipv implements java.io.Serializable {

	private int lipvListaPrecvta;
	private SistMone sistMone;
	private String lipvNombre;
	private boolean lipvModifMoneda;
	private boolean lipvConImpuestos;
	private Date lipvFechaVigDes;
	private Date lipvFechaVigHas;
	private boolean lipvUtilizable;
	private boolean lipvModPrecioNp;
	private boolean lipvEsOferta;
	private boolean lipvHabPromVol;
	private short lipvCalculoConMargen;
	private short lipvEsListaRef;
	private short lipvEsListaAcopio;
	private Set ventArpvs = new HashSet(0);

	public VentLipv() {
	}

	public VentLipv(int lipvListaPrecvta, SistMone sistMone, String lipvNombre, boolean lipvModifMoneda,
			boolean lipvConImpuestos, Date lipvFechaVigDes, Date lipvFechaVigHas, boolean lipvUtilizable,
			boolean lipvModPrecioNp, boolean lipvEsOferta, boolean lipvHabPromVol, short lipvCalculoConMargen,
			short lipvEsListaRef, short lipvEsListaAcopio) {
		this.lipvListaPrecvta = lipvListaPrecvta;
		this.sistMone = sistMone;
		this.lipvNombre = lipvNombre;
		this.lipvModifMoneda = lipvModifMoneda;
		this.lipvConImpuestos = lipvConImpuestos;
		this.lipvFechaVigDes = lipvFechaVigDes;
		this.lipvFechaVigHas = lipvFechaVigHas;
		this.lipvUtilizable = lipvUtilizable;
		this.lipvModPrecioNp = lipvModPrecioNp;
		this.lipvEsOferta = lipvEsOferta;
		this.lipvHabPromVol = lipvHabPromVol;
		this.lipvCalculoConMargen = lipvCalculoConMargen;
		this.lipvEsListaRef = lipvEsListaRef;
		this.lipvEsListaAcopio = lipvEsListaAcopio;
	}

	public VentLipv(int lipvListaPrecvta, SistMone sistMone, String lipvNombre, boolean lipvModifMoneda,
			boolean lipvConImpuestos, Date lipvFechaVigDes, Date lipvFechaVigHas, boolean lipvUtilizable,
			boolean lipvModPrecioNp, boolean lipvEsOferta, boolean lipvHabPromVol, short lipvCalculoConMargen,
			short lipvEsListaRef, short lipvEsListaAcopio, Set ventArpvs) {
		this.lipvListaPrecvta = lipvListaPrecvta;
		this.sistMone = sistMone;
		this.lipvNombre = lipvNombre;
		this.lipvModifMoneda = lipvModifMoneda;
		this.lipvConImpuestos = lipvConImpuestos;
		this.lipvFechaVigDes = lipvFechaVigDes;
		this.lipvFechaVigHas = lipvFechaVigHas;
		this.lipvUtilizable = lipvUtilizable;
		this.lipvModPrecioNp = lipvModPrecioNp;
		this.lipvEsOferta = lipvEsOferta;
		this.lipvHabPromVol = lipvHabPromVol;
		this.lipvCalculoConMargen = lipvCalculoConMargen;
		this.lipvEsListaRef = lipvEsListaRef;
		this.lipvEsListaAcopio = lipvEsListaAcopio;
		this.ventArpvs = ventArpvs;
	}

	public int getLipvListaPrecvta() {
		return this.lipvListaPrecvta;
	}

	public void setLipvListaPrecvta(int lipvListaPrecvta) {
		this.lipvListaPrecvta = lipvListaPrecvta;
	}

	public SistMone getSistMone() {
		return this.sistMone;
	}

	public void setSistMone(SistMone sistMone) {
		this.sistMone = sistMone;
	}

	public String getLipvNombre() {
		return this.lipvNombre;
	}

	public void setLipvNombre(String lipvNombre) {
		this.lipvNombre = lipvNombre;
	}

	public boolean isLipvModifMoneda() {
		return this.lipvModifMoneda;
	}

	public void setLipvModifMoneda(boolean lipvModifMoneda) {
		this.lipvModifMoneda = lipvModifMoneda;
	}

	public boolean isLipvConImpuestos() {
		return this.lipvConImpuestos;
	}

	public void setLipvConImpuestos(boolean lipvConImpuestos) {
		this.lipvConImpuestos = lipvConImpuestos;
	}

	public Date getLipvFechaVigDes() {
		return this.lipvFechaVigDes;
	}

	public void setLipvFechaVigDes(Date lipvFechaVigDes) {
		this.lipvFechaVigDes = lipvFechaVigDes;
	}

	public Date getLipvFechaVigHas() {
		return this.lipvFechaVigHas;
	}

	public void setLipvFechaVigHas(Date lipvFechaVigHas) {
		this.lipvFechaVigHas = lipvFechaVigHas;
	}

	public boolean isLipvUtilizable() {
		return this.lipvUtilizable;
	}

	public void setLipvUtilizable(boolean lipvUtilizable) {
		this.lipvUtilizable = lipvUtilizable;
	}

	public boolean isLipvModPrecioNp() {
		return this.lipvModPrecioNp;
	}

	public void setLipvModPrecioNp(boolean lipvModPrecioNp) {
		this.lipvModPrecioNp = lipvModPrecioNp;
	}

	public boolean isLipvEsOferta() {
		return this.lipvEsOferta;
	}

	public void setLipvEsOferta(boolean lipvEsOferta) {
		this.lipvEsOferta = lipvEsOferta;
	}

	public boolean isLipvHabPromVol() {
		return this.lipvHabPromVol;
	}

	public void setLipvHabPromVol(boolean lipvHabPromVol) {
		this.lipvHabPromVol = lipvHabPromVol;
	}

	public short getLipvCalculoConMargen() {
		return this.lipvCalculoConMargen;
	}

	public void setLipvCalculoConMargen(short lipvCalculoConMargen) {
		this.lipvCalculoConMargen = lipvCalculoConMargen;
	}

	public short getLipvEsListaRef() {
		return this.lipvEsListaRef;
	}

	public void setLipvEsListaRef(short lipvEsListaRef) {
		this.lipvEsListaRef = lipvEsListaRef;
	}

	public short getLipvEsListaAcopio() {
		return this.lipvEsListaAcopio;
	}

	public void setLipvEsListaAcopio(short lipvEsListaAcopio) {
		this.lipvEsListaAcopio = lipvEsListaAcopio;
	}

	public Set getVentArpvs() {
		return this.ventArpvs;
	}

	public void setVentArpvs(Set ventArpvs) {
		this.ventArpvs = ventArpvs;
	}

}
