package ar.com.rollpaper.pricing.beans;
// Generated 24/05/2018 09:15:54 by Hibernate Tools 5.3.0.Beta2

/**
 * VentArpvId generated by hbm2java
 */
public class VentArpvId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int arpvArticulo;
	private int arpvListaPrecvta;

	public VentArpvId() {
	}

	public VentArpvId(int arpvArticulo, int arpvListaPrecvta) {
		this.arpvArticulo = arpvArticulo;
		this.arpvListaPrecvta = arpvListaPrecvta;
	}

	public int getArpvArticulo() {
		return this.arpvArticulo;
	}

	public void setArpvArticulo(int arpvArticulo) {
		this.arpvArticulo = arpvArticulo;
	}

	public int getArpvListaPrecvta() {
		return this.arpvListaPrecvta;
	}

	public void setArpvListaPrecvta(int arpvListaPrecvta) {
		this.arpvListaPrecvta = arpvListaPrecvta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VentArpvId))
			return false;
		VentArpvId castOther = (VentArpvId) other;

		return (this.getArpvArticulo() == castOther.getArpvArticulo())
				&& (this.getArpvListaPrecvta() == castOther.getArpvListaPrecvta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getArpvArticulo();
		result = 37 * result + this.getArpvListaPrecvta();
		return result;
	}

}
