USE [RPAPER]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO										

CREATE TABLE [dbo].[PRIC_DESCUENTO_X_FAMILIAS](
	[PRIC_FAMILIA_ID] [int] NOT NULL,
	[PRIC_FAMILIA_CLIENTE] [int] NOT NULL,
	[PRIC_FAMILIA_LISTA_PRECVTA] [int] NOT NULL,
	[PRIC_FAMILIA_DESCUENTO_1]  [int] NOT NULL,
	[PRIC_FAMILIA_DESCUENTO_2] [decimal](14, 2) NOT NULL,	
	[PRIC_FAMILIA_FECHA_DESDE] [datetime] NOT NULL,
	[PRIC_FAMILIA_FECHA_HASTA] [datetime] NOT NULL,
	[PRIC_REFERENCIA] [varchar](100) NULL

 CONSTRAINT [PRIC_PK2] PRIMARY KEY CLUSTERED 
(
	[PRIC_FAMILIA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]  
GO


